"""Comunas de Chile por región (16 regiones). Incluye algunos alias y localidades frecuentes."""

REGIONES = {
    "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
    "Tarapacá": ["Iquique", "Alto Hospicio", "Pozo Almonte", "Camiña", "Colchane", "Huara", "Pica"],
    "Antofagasta": ["Antofagasta", "Mejillones", "Sierra Gorda", "Taltal", "Calama", "Ollagüe",
                    "San Pedro de Atacama", "Tocopilla", "María Elena"],
    "Atacama": ["Copiapó", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Vallenar",
                "Alto del Carmen", "Freirina", "Huasco"],
    "Coquimbo": ["La Serena", "Coquimbo", "Andacollo", "La Higuera", "Paihuano", "Paiguano", "Vicuña",
                 "Illapel", "Canela", "Los Vilos", "Salamanca", "Ovalle", "Combarbalá", "Monte Patria",
                 "Punitaqui", "Río Hurtado", "Tongoy"],
    "Valparaíso": ["Valparaíso", "Casablanca", "Casa Blanca", "Concón", "Juan Fernández", "Puchuncaví", "Quintero",
                   "Viña del Mar", "Isla de Pascua", "Los Andes", "Calle Larga", "Rinconada",
                   "San Esteban", "La Ligua", "Cabildo", "Papudo", "Petorca", "Zapallar", "Quillota",
                   "La Calera", "Calera", "Hijuelas", "La Cruz", "Nogales", "San Antonio", "Algarrobo",
                   "Cartagena", "El Quisco", "El Tabo", "Santo Domingo", "San Felipe", "Catemu",
                   "Llaillay", "Llay-Llay", "Llay Llay", "Panquehue", "Putaendo", "Santa María",
                   "Quilpué", "Limache", "Olmué", "Villa Alemana", "Reñaca"],
    "Metropolitana": ["Santiago", "Cerrillos", "Cerro Navia", "Conchalí", "El Bosque", "Estación Central",
                      "Huechuraba", "Independencia", "La Cisterna", "La Florida", "La Granja", "La Pintana",
                      "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipú",
                      "Ñuñoa", "Pedro Aguirre Cerda", "Peñalolén", "Providencia", "Pudahuel", "Quilicura",
                      "Quinta Normal", "Recoleta", "Renca", "San Joaquín", "San Miguel", "San Ramón",
                      "Vitacura", "Puente Alto", "Pirque", "San José de Maipo", "Colina", "Lampa", "Tiltil",
                      "Til Til", "San Bernardo", "Buin", "Calera de Tango", "Paine", "Melipilla", "Alhué",
                      "Curacaví", "María Pinto", "San Pedro", "Talagante", "El Monte", "Isla de Maipo",
                      "Padre Hurtado", "Peñaflor", "Chicureo"],
    "O'Higgins": ["Rancagua", "Codegua", "Coinco", "Coltauco", "Doñihue", "Graneros", "Las Cabras",
                  "Machalí", "Malloa", "Mostazal", "San Francisco de Mostazal", "Olivar", "Peumo",
                  "Pichidegua", "Quinta de Tilcoco", "Rengo", "Requínoa", "San Vicente",
                  "San Vicente de Tagua Tagua", "Pichilemu", "La Estrella", "Litueche", "Marchigüe",
                  "Marchihue", "Navidad", "Paredones", "San Fernando", "Chépica", "Chimbarongo", "Lolol",
                  "Nancagua", "Palmilla", "Peralillo", "Placilla", "Pumanque", "Santa Cruz"],
    "Maule": ["Talca", "Constitución", "Curepto", "Empedrado", "Maule", "Pelarco", "Pencahue", "Río Claro",
              "San Clemente", "San Rafael", "Cauquenes", "Chanco", "Pelluhue", "Curicó", "Hualañé",
              "Licantén", "Molina", "Rauco", "Romeral", "Sagrada Familia", "Teno", "Vichuquén", "Linares",
              "Colbún", "Longaví", "Parral", "Retiro", "San Javier", "Villa Alegre", "Yerbas Buenas"],
    "Ñuble": ["Chillán", "Chillán Viejo", "Bulnes", "El Carmen", "Pemuco", "Pinto", "Quillón", "San Ignacio",
              "Yungay", "Quirihue", "Cobquecura", "Coelemu", "Ninhue", "Portezuelo", "Ránquil", "Treguaco",
              "San Carlos", "Coihueco", "Ñiquén", "San Fabián", "San Nicolás"],
    "Biobío": ["Concepción", "Coronel", "Chiguayante", "Florida", "Hualqui", "Lota", "Penco",
               "San Pedro de la Paz", "Santa Juana", "Talcahuano", "Tomé", "Hualpén", "Lebu", "Arauco",
               "Cañete", "Contulmo", "Curanilahue", "Los Álamos", "Tirúa", "Los Ángeles", "Antuco",
               "Cabrero", "Laja", "Mulchén", "Nacimiento", "Negrete", "Quilaco", "Quilleco", "San Rosendo",
               "Santa Bárbara", "Tucapel", "Yumbel", "Alto Biobío"],
    "Araucanía": ["Temuco", "Carahue", "Cunco", "Curarrehue", "Freire", "Galvarino", "Gorbea", "Lautaro",
                  "Loncoche", "Melipeuco", "Nueva Imperial", "Padre Las Casas", "Perquenco", "Pitrufquén",
                  "Pucón", "Saavedra", "Teodoro Schmidt", "Toltén", "Vilcún", "Villarrica", "Cholchol",
                  "Angol", "Collipulli", "Curacautín", "Ercilla", "Lonquimay", "Los Sauces", "Lumaco",
                  "Purén", "Renaico", "Traiguén", "Victoria"],
    "Los Ríos": ["Valdivia", "Corral", "Lanco", "Los Lagos", "Máfil", "Mariquina", "San José de la Mariquina",
                 "Paillaco", "Panguipulli", "La Unión", "Futrono", "Lago Ranco", "Río Bueno", "Niebla",
                 "Coñaripe", "Liquiñe"],
    "Los Lagos": ["Puerto Montt", "Calbuco", "Cochamó", "Fresia", "Frutillar", "Los Muermos", "Llanquihue",
                  "Maullín", "Puerto Varas", "Castro", "Ancud", "Chonchi", "Curaco de Vélez", "Dalcahue",
                  "Puqueldón", "Queilén", "Quellón", "Quemchi", "Quinchao", "Osorno", "Puerto Octay",
                  "Purranque", "Puyehue", "Río Negro", "San Juan de la Costa", "San Pablo", "Chaitén",
                  "Futaleufú", "Hualaihué", "Palena", "Achao", "Alerce", "Entre Lagos"],
    "Aysén": ["Coyhaique", "Coihaique", "Lago Verde", "Aysén", "Aisén", "Puerto Aysén", "Cisnes", "Guaitecas",
              "Cochrane", "O'Higgins", "Tortel", "Chile Chico", "Río Ibáñez"],
    "Magallanes": ["Punta Arenas", "Laguna Blanca", "Río Verde", "San Gregorio", "Cabo de Hornos", "Antártica",
                   "Porvenir", "Primavera", "Timaukel", "Natales", "Puerto Natales", "Torres del Paine",
                   "Puerto Williams"],
}

# Cómo aparece el nombre de la región en los textos ("Región de ...")
NOMBRE_REGION = {
    "Arica y Parinacota": ["arica y parinacota"], "Tarapacá": ["tarapaca"], "Antofagasta": ["antofagasta"],
    "Atacama": ["atacama"], "Coquimbo": ["coquimbo"], "Valparaíso": ["valparaiso"],
    "Metropolitana": ["metropolitana"], "O'Higgins": ["o'higgins", "ohiggins", "libertador"],
    "Maule": ["maule"], "Ñuble": ["nuble"], "Biobío": ["biobio", "bio bio", "bio-bio"],
    "Araucanía": ["araucania"], "Los Ríos": ["los rios"], "Los Lagos": ["los lagos"],
    "Aysén": ["aysen", "aisen"], "Magallanes": ["magallanes"],
}
